name: random_unicode
description: A library to generate random Unicode strings within the given range(s).
version: 0.2.4
homepage: https://aiurovet.com/
repository: https://github.com/aiurovet/random_unicode/

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies: 
  lim: ^0.1.6

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.0
